---
title: 'U6614: Assignment 3: Subway Fare Evasion Microdata'
author: "Your Name (your-uni)"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
    toc_depth: '3'
    number_sections: yes
  html_document:
    toc: yes
    toc_depth: '3'
    toc_float: yes
    number_sections: yes
    highlight: tango
    theme: default
    fig_caption: yes
    df_print: tibble
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

##### *Please submit your knitted .pdf file along with the corresponding R markdown (.rmd) via Courseworks by 11:59pm on the due date.* {-}

\medspace

# Load libraries.


\medspace

# Load and inspect the two public defender client datasets (BDS & LAS). 

- Get a good look at the data, but don't print long, clunky output here; one approach is to call the str() function for each dataset but to suppress the included list of attributes by including the option give.attr = FALSE.

### 2a) Give a brief overview of the data. The aim is not be exhaustive, but to paint a picture of they key features of the data with respect to the policy questions you'll be exploring. {-}


### 2b) For each dataset, what is the unit of observation and population represented by this "sample"? Do you think this sample does a good job representing the population of interest? Why or why not? {-}


### 2c) Inspect and describe the coding of race and ethnicity in each dataset. {-}


### 2d) From the outset, are there any data limitations you think are important to note? {-}


\medspace

# Clean BDS race and ethnicity data (insert code chunks that only include code you used to recode and very briefly validate your recoding).


### 3a) BDS: race data (generate column `race_clean`). {-}


### 3b) BDS: ethnicity data (generate column `ethnicity_clean`). {-}


### 3c) Generate a single race/ethnicity factor variable `race_eth` with mutually exclusive categories. {-}


\medspace

# Clean LAS race and ethnicity data

### 4a) Follow your own steps to end up at a comparably coded `race_eth` variable for the LAS data. {-}

*NOTE: you may be able to do everything in a single pipe, depending on your approach (but you certainly don't have to).*


\medspace

# Combining (appending) the BDS and LAS microdata 

### 5a) Create a column (`pd`) to identify public defender data source. {-}

### 5b) Append `arrests_bds.clean` and `arrests_las.clean` using `bind_rows()`. Store as new data frame `arrests.clean` and inspect for consistency/accuracy. {-}

### 5c) What is the total number of subway fare evasion arrest records? {-}

### 5d) Save `arrests.clean` as an .RData file, in a folder for next class called Lecture4. {-}

\medspace


# Descriptive statistics by race/ethnicity

### 6a) Print the number of arrests for each race/ethnicity category (a frequency table). {-}

### 6b) Print the proportion of total arrests for each race/ethnicity category. How does excluding NAs change the results? {-}

### 6c) Show the average age, share male, and dimissal rate for each race/ethnicity category. Include the total sample size (all observations), and if you can, include the sample size for the dismissal variabe as well (number of non-NA observations). {-}

### 6d) Describe any noteworthy findings from the table you presented in 6c. {-}


\medspace

# Subway-station level analysis

### 7a) Create dummy variables for each race/ethnicity category and show summary statistics only for these dummy variables. {-}


### 7b) Aggregate to station-level observations and show a table with the top 10 stations by arrest totals, including the following information for each station: {-}
 
- station name (loc2)
- station id
- total number of arrests at each station
- total number of arrests for each race_eth category at each station
- sort in descending order by total number of arrests
- remember to only show the top 10 stations
- use kable() in the knitr package for better formatting


###  7c) Aggregate to station-level observations (group by loc2), and show a table of stations with at least 50 arrests along with the following information: {-}

- station name (loc2)
- station arrest total
- combined total number of Black and Hispanic arrests
- total number of arrests with race/ethnicity coded as NA
- share of arrests that are Black and Hispanic (excluding race_eth = NA from denominator)
- sorted in ascending order by Black and Hispanic arrest share
- remember to only show stations with at least 50 total arrests
- use kable() in the knitr package for better formatting

### 7d) Briefly summarize any noteworthy findings from the table you just generated. {-}

\medspace

# (OPTIONAL) Visualize the distribution of arrests by race/ethnicity at stations with more than 100 arrests.
- Hint: see R code from class, section 8


