---
title: 'U6614 Assignment 5: \break Water shutoffs, race, and income in Detroit: \break Which communities have been hardest hit?'
author: "YOUR NAME"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
    toc_depth: '3'
    number_sections: yes
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    highlight: tango
    theme: default
    fig_caption: yes
    df_print: tibble
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

##### *Please submit your knitted .pdf file along with the corresponding R markdown (.rmd) via Courseworks by 11:59pm on Monday, November 1st.* {-}

##### Remember to think carefully about what code you include in your knitted document. Only include code chunks that you need to generate the plots and statistics to answer the questions below. Don't include code from your working R script (that we started in class) that was only used to inspect and validate your results, and isn't necessary to answer the questions. {-}

\medspace

# Load libraries {-}

\medspace


# "Cross-sectional" analysis

- In this section we'll explore variation in shutoffs *across* Census tracts (one observation per Census tract, summing shutoffs over the whole time period).

### 1a) Visualize and interpret the relationship between share Black and shutoffs per capita across census tracts in Detroit. {-}


### 1b) Visualize and interpret the relationship between median income and shutoffs per capita across census tracts in Detroit. {-}


### 1c) Visualize and interpret how shutoffs per capita relate to both Black share and median income on the ***same*** plot. Does race or income appear to be more salient? {-}

\medspace


# Time-series analysis.

- In this section, we'll explore variation *between* different groups of Census tracts and over time *within* groups (with groups defined based on tract-level income and racial composition).

### 2a) Plot and interpret the shutoffs per capita over time for tracts below/above citywide median housheold income (show two time series on a single plot). {-}

### 2b) Plot and interpret the shutoffs per capita over time for tracts that are at least 75% Black and those that aren't (show two time series on a single plot). {-}

\medspace

# Conclusion

### 3a) Based on the "cross-sectional" and time series analysis conducted above, does race or income appear to be a more important factor for explaining what type of households are most affected by the public water shutoffs? Explain. {-}

