---
title: 'U6614: Assignment 2: Assessing gender wage gaps using the Current Population Survey'
author: "Your Name (your-uni)"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
    toc_depth: '3'
    number_sections: yes
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    highlight: haddock
    theme: default
    fig_caption: yes
    df_print: tibble
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

##### *Please submit your knitted .pdf file along with the corresponding R markdown (.rmd) via Courseworks by 11:59pm on Monday, September 27.* {-}

\medspace

*Before knitting your rmd file as a pdf, you will need to install TinyTex for Latex distribution by running the following code:*

`tinytex::install_tinytex()`

*Please visit [this](https://bookdown.org/yihui/rmarkdown-cookbook/install-latex.html) link for more information on TinyTex installation.*

\medspace

# Load and inspect CPS data: 

### a) Inspect the data frame and data types for each column {-}
- make sure to inspect the age, sex, race, college columns

### b) Use the mutate function to create new column for sex {-}
- sex.fac = as.factor(sex),
- check if it worked by calling the str() function

### c) Include sex.fac in a new data frame called cps.temp1 {-}
- also create factors for race and college education,
- use a pipe to exclude the columns for serial, ind
- after creating cps.temp1, print the first 5 observations

### d) Inspect race.fac, sex.fac, and college.fac using the levels() function {-}
- what package is the levels() function located in?

### e) Use filter() to only include rows only for June 2020 {-}
- store as a new object cps_2020,
- print the first 5 observations,
- confirm your data only includes observations for 2020

### f) Remove the cps.temp1 object from memory using the rm() function {-}

\medspace

# Describe the cps_2020 data frame

### a) What is the unit of observation? {-}

### b) How many individuals are observed? from how many households? {-}

### c) What is the average age of individuals in the sample? Youngest and oldest person? {-}

\medspace

# Earnings per week for different groups in June 2020

### a) Find the observation for the top weekly earnings using the summarise() function {-}
- assign this to a new object called max_earnings

### b) Find max weekly earnings using the arrange function instead of summarise {-}

### c) Use the filter function to subset for the observation with max weekly earnings {-}
- don't hardcode the max earnings to filter on, refer to the max_earnings object from a),
- store in new data frame cps_max_earn,
- confirm it worked

### d) What is the age, sex, and race of the top weekly earner in the sample? {-}

### e) List the age, sex, and race of the top 10 weekly earners in the sample {-}

### f) How many individuals earned more than $2000 in weekly earnings? {-}

\medspace

# Wage gaps between males and females:

### a) Use the filter function to subset observations for males {-}
- assign to new data frame, cps_2020_male,
- sort in descending order of weekly earnings
- check if it worked

### b) Repeat part a for females and create a new data frame, cps_2020_female {-}

### c) Use summarise to find mean, min & max for males and females, separately {-}
- name each statistic appropriately (i.e. name each column in the 1-row table of stats)
- what is the gender gap in mean weekly earnings?

### d) What is the wage gap in weekly earnings between white males and Black females? {-}

### e) What is the wage gap between college educated white males and college educated Black females? {-}

\medspace

*NOTE: the exercises above are done using weekly earnings, but can easily be converted to hourly wages*


